package com.example.documents.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.documents.model.enums.Sex;
import lombok.Data;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "document")
@Data
public class Document {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String name;
    private String surname;
    private String birthday;
    @DynamoDBTypeConvertedEnum
    private Sex sex;
}
