package com.example.documents.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.example.documents.model.dto.requests.metadata.DocumentMetadata;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;

@DynamoDBTable(tableName = "document")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
//@RequiredArgsConstructor
public class Document {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String userId;
    private DocumentMetadata documentMetadata;
    @DynamoDBTypeConvertedEnum
    private LocalDate createdDate = LocalDate.now();

    @Override
    public int hashCode() {
        return 35;
    }
}
