spring:
  kafka:
    bootstrap-servers: 174.22.22.55:9092
kafka:
  topic: user
  bootstrapAddress: localhost:29092
  bootstrap:
    servers: localhost:29092
  groupId: localhost:9092
#kafka:
#  topic: "rbp.event.audit.pub"
#  bootstrap:
#    servers: localhost:9092
#  security:
#  protocol: "SASL_PLAINTEXT"
amazon:
  dynamodb:
    endpoint: http://localhost:9000
    amazonAWSAccessKey: cifra
    secretkey: qAzXsw1!
  aws:
    region: eu-west-1
minio:
  access-key: admin
  secret-key: admin_password
  bucket: documents
  template-bucket: template
management:
  endpoints.web.exposure.include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true